### ISSUE TITLE
Cannot find arf files on neurobank

### ISSUE THREAD

**Issue by SMMoseley** [melizalab/melizalab-tools#5]
group-kilo-spikes -o . C194_3_1.arf .

- group-kilo-spikes version 2023.07.19
- using stimulus times from C194_3_1.arf
  - registered at https://gracula.psyc.virginia.edu/neurobank/resources/C194_3_1/
- kilosort output directory: .
  - spike times: spike_times.npy
  - spike clusters: spike_clusters.npy
  - cluster info: cluster_info.tsv
  - filtered recording: temp_wh.dat
    - 104894400 samples, 128 channels
  - warning: removing spikes with duplicate times from clusters 68,270,270
Traceback (most recent call last):
  File "/home/melizalab/.local/bin/group-kilo-spikes", line 8, in <module>
    sys.exit(run_group_spikes())
  File "/home/melizalab/.local/pipx/venvs/melizalab-tools/lib/python3.8/site-packages/dlab/kilo.py", line 519, in run_group_spikes
    anyio.run(group_spikes_script)
  File "/home/melizalab/.local/pipx/venvs/melizalab-tools/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/melizalab/.local/pipx/venvs/melizalab-tools/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/melizalab/.local/pipx/venvs/melizalab-tools/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/melizalab/.local/pipx/venvs/melizalab-tools/lib/python3.8/site-packages/dlab/kilo.py", line 392, in group_spikes_script
    datafile = await nbank.find_resource(
  File "/home/melizalab/.local/pipx/venvs/melizalab-tools/lib/python3.8/site-packages/dlab/nbank.py", line 46, in find_resource
    response.raise_for_status()
  File "/home/melizalab/.local/pipx/venvs/melizalab-tools/lib/python3.8/site-packages/httpx/_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://gracula.psyc.virginia.edu/neurobank/resources/C194_3_1.arf/locations/'
For more information check: https://httpstatuses.com/404

**Comment by dmeliza** [comment]
I'm not sure why this error is occurring, but it appears to be fixed in the most recent version of melizalab-tools (2023.09.07; script version 2023.08.25).

I strongly recommend creating a separate directory to store the output files. Then your command will look like this:

`group-kilo-spikes -o C194_3_1 C194_3_1.arf C194_2023-10-16_19-44-01_chorus/Record\ Node\ 104/experiment1/recording1/continuous/Rhythm_FPGA-100.0/`

Even better, create the output directory first and tell kilosort to save its output files there, so you don't have to type in a big long path to get there.
